# Generated by Django 4.1.2 on 2023-01-03 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flows',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
